package provider

// Role identifies the author of a Message in a chat conversation. It
// is normalized across providers; implementations translate it to
// whatever the upstream API expects.
type Role string

// Standard roles supported across providers.
const (
	// RoleSystem carries instructions that steer the model's behavior.
	RoleSystem Role = "system"
	// RoleUser carries input from the end user.
	RoleUser Role = "user"
	// RoleAssistant carries prior model output, e.g. in multi-turn history.
	RoleAssistant Role = "assistant"
)

// Message is a single turn in a chat conversation.
type Message struct {
	// Role identifies who authored Content.
	Role Role
	// Content is the textual content of the message.
	Content string
}

// ChatRequest is the gateway's normalized representation of a chat
// completion request, independent of any specific upstream provider.
type ChatRequest struct {
	// Model is the upstream model identifier to route the request to
	// (e.g. "gpt-4o", "claude-sonnet-5").
	Model string
	// Messages is the conversation history, oldest first.
	Messages []Message
	// MaxTokens caps the number of tokens the model may generate.
	MaxTokens int
	// Temperature controls sampling randomness; typically in [0, 2].
	Temperature float64
	// Stream indicates the caller wants an incremental response via
	// Provider.ChatCompletionStream rather than Provider.ChatCompletion.
	Stream bool
}

// ChatResponse is the gateway's normalized representation of a
// completed (non-streaming) chat completion response.
type ChatResponse struct {
	// ID is the upstream provider's unique identifier for this response.
	ID string
	// Model is the upstream model that actually served the request.
	Model string
	// Choices holds the generated completion(s). Most requests yield
	// exactly one, but providers may return more.
	Choices []Choice
	// Usage reports token accounting for the request.
	Usage Usage
}

// Choice is one generated completion within a ChatResponse.
type Choice struct {
	// Index is the choice's position within ChatResponse.Choices.
	Index int
	// Message is the generated message.
	Message Message
	// FinishReason indicates why generation stopped (e.g. "stop",
	// "length"), as normalized/reported by the provider.
	FinishReason string
}

// Usage reports token accounting for a chat completion request.
type Usage struct {
	// PromptTokens is the number of tokens in the input messages.
	PromptTokens int
	// CompletionTokens is the number of tokens generated by the model.
	CompletionTokens int
	// TotalTokens is PromptTokens + CompletionTokens.
	TotalTokens int
}
